#!/bin/bash
path="../../../blender-2.79-e045fe53f1b0-linux-glibc217-x86_64/" # path to your local blender folder (Download from https://download.blender.org/release/Blender2.79/latest/)
cd tools/terrain-2020 && ${path}blender terrain.blend -y
